---
Name: shortcodable
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'restruct/silverstripe-shortcodable:client/dist/js/editor_plugin.js'
    - 'restruct/silverstripe-shortcodable:client/dist/js/shortcodable.js'
    # Require simpler object & jQuery/BootstrapJS/VueJS from SimplerSilverstripe module
    - 'restruct/silverstripe-simpler:client/dist/js/simpler-silverstripe.js'
  extra_requirements_css:
    - 'restruct/silverstripe-shortcodable:client/dist/styles/shortcodable.css'

Shortcodable\Shortcodable:
  htmleditor_names:
    - cms

SilverStripe\TinyMCE\TinyMCEConfig:
  editor_css:
    - 'restruct/silverstripe-shortcodable:client/dist/styles/editor.css'

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Shortcodable\Controllers\ShortcodableAdminController

SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  extensions:
    - Shortcodable\Extensions\HtmlEditorFieldExtension

SilverStripe\View\Parsers\ShortcodeParser:
  extensions:
    - Shortcodable\Extensions\ShortcodeParserExtension

